version: '3'

services:
  db:
    image: library/mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: amazing-spring
      MYSQL_ROOT_PASSWORD: amazing-rest-api
